package it.polimi.ingsw.network.message;

public enum MessageType {
    LOGIN_REQUEST, LOGIN_REPLY,
    ADD_PLAYER_REQUEST, PLAYER_SEND,
    NEW_GAME_REQUEST,
    DELETE_GAME_REQUEST,

    CHOSE_TEAM,
    CHOSE_TOWER,TOWER_SEND,

    GAME_SEND,
    MOVE_STUDENT_ISLAND,MOVE_STUDENT_DASHBOARD,
    MOVE_MOTHER_NATURE,
    TAKE_FROM_CLOUD,
    SELECT_ASSISTANT,
    USE_CHARACTER,

    WIN,
    LOSE
}
